.gitignore
_stylesheets/vendor/_rouge.scss
_stylesheets/vendor/_workable.scss

Fixes a broken build, introduced by #13, by adding missing Sass stylesheets that were missed due to the _.gitignore_ ignoring all directories named `vendor`.

fix(styles): add missing Sass files and update the gitignore

---

blog-posts.html
featured-projects.html

This is an attempt to address https://github.com/godaddy/godaddy.github.io/issues/17 using Materialize's [built-in grid utilities](https://materializecss.com/grid.html). Additionally, this provides some very basic responsiveness to both the featured projects **and** the blog posts, so we can have a consistent experience across the site. Here are some screenshots to expedite the review process:

Display multiple project cards per row on large screens

---

blog-posts.html
featured-projects.html

This PR reverts commit aadfab1564fd95857111b1d6c60c29a2cad6078b until we have a solution for responsive card content that also results in uniform card heights. CC (@SivanMehta)
_Current Projects_
_After Revert_
_Current Blog Index_
_After Revert_

revert(styles): responsive featured projects and blog posts

---

_includes/component/project-card.html
_stylesheets/base/_typography.scss
blog-posts.html
featured-projects.html

This PR resolves #17 by utilizing the [small Materialize card](https://materializecss.com/cards.html#sizes) size class for project cards for medium screen sizes and above. All cards have been updated to elevate on hover, like the official [Material Design card elevation behavior](https://material.io/design/components/cards.html#behavior).
_Note: these cards look really nice [rendered 3-up on large screens](https://user-images.githubusercontent.com/1934719/39910868-0a8d139a-54ae-11e8-86a8-734a94f7e42d.png), but some of the current card descriptions won't fit without style changes, text edits, or truncation. I'm deferring those decisions for future work._
_Desktop_
_Blog Index_
_Nexus 6_
_iPhone 6_
_iPhone Air 2_

feat(projects): render project cards with a uniform height

---

_data/social.json
_includes/component/social-links.html
_includes/section/footer.html

This PR moves the social profiles from hard-coded HTML into a JSON data file. It also adds a link to [GoDaddy on Dribble](https://dribbble.com/GoDaddy).
_Updated footer_

refactor(social-links): use a data file to define the footer social links

---

_layouts/post.html
_posts/2018-04-04-isomorphic-asset-system-for-react-and-react-native.md
_posts/2018-05-15-jiractl.md
_stylesheets/layout/_post.scss

This PR was pulled from #42 (see screenshots there), and adds an optional, full-bleed cover image for blog posts with featured images that look nice full width.

feat(post): add an optional, full-bleed featured image to the blog posts

---

_posts/2018-02-22-announcing-terminus.md
_posts/2018-04-02-introducing-eslint-plugin-i18n-json.md
_posts/2018-05-02-kubernetes-introduction-for-developers.md
_posts/2018-05-15-jiractl.md
_stylesheets/base/_typography.scss

Pulled from #42 (see screenshots there), this PR adds an optional, decorative drop cap for blog posts with enough lead text to support it. It also fixes up the headlines in one article that was rendering a bunch of `<h1>` tags onto the page.

feat(post): add an optional drop cap feature for blog post layouts

---

_layouts/post.html
_posts/2018-05-15-jiractl.md

Missed when separating #42, this removes the authors from the top of the blog post. They are now at the bottom.
Also removes the full-bleed featured image from the jiractl article, because it looks bad on 4K+ monitors.

fix(post): remove duplicate authors panel from layout

---

_data/projects.json
_includes/block/scripts.html
_includes/component/project-card.html
_includes/component/project-search.html
_includes/scripts/filter-projects.js
featured-projects.html

This PR implements simple project searching on the Featured Projects page using [Fuse.js](http://fusejs.io) and jQuery. I've opened #48 to get some thoughts on ways we can manage and better serve JS, since this project is frequently increasing in custom and vendor JS scripts.
_Note: I'm going to open a PR to add back rendering the lead maintainer. Then that field being searchable will seem less unexpected._
_Chrome 67 on macOS High Sierra_
_Safari on iPhone X_

feat(projects): make featured projects searchable

---

_config.yml
_includes/block/head.html

This PR enables the optional [Atom (RSS) feed plugin](https://help.github.com/articles/atom-rss-feeds-for-github-pages/) built into GitHub Pages.

feat(atom): enable the Atom (RSS) feed plugin

---

_includes/block/head.html
blog-posts.html
code-of-conduct.html
featured-projects.html

Add open-graph page metadata for social sharing

---

_includes/block/head.html

Does not look great now: https://twitter.com/dnasevic/status/1052098536953839616
Twitter cards should work with open-graph data per the description at the end of [this](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started) article. I think what's missing here is the `twitter:card` definition and we don't have to duplicate the open-graph to twitter meta data.
Twitter Card validator for testing: https://cards-dev.twitter.com/validator

Add page metadata for Twitter card

---

_includes/component/recent-posts.html
index.html

This PR introduces a new recent posts card to the home page.

feat: add new recent posts card to the home page

---

README.md

This PR adds instructions on developing in a fork and distributing previews of those changes via GitHub Pages.

doco: add instructions on distributing a fork preview

---

_config.yml
blog.html
projects.html

I've often felt these routes are unnecessarily overqualified: _featured_ projects, _blog_ posts. This PR updates those page routes to be more concise, and [adds redirects](https://help.github.com/articles/redirects-on-github-pages/) for the legacy paths.

feat: update /blog and /projects routes to be more concise

---

_config.yml
blog-posts.html
featured-projects.html

Reverts godaddy/godaddy.github.io#85 because something is wrong with the "projects" route.

Revert "feat: update /blog and /projects routes to be more concise"

---

_stylesheets/layout/_post.scss

I have a large monitor, so viewing articles on them looks a little silly:
I removed the maximum width of the articles to simply use Bootstrap's `.container` instead (which these articles already use)
Mobile-width viewing is unchanged.

Fix large monitor width

---

README.md
_config.yml
_includes/component/navigation.html
index.html

The current blog name is confusing some folks who think the intention is to blog only about open source contributions. Proposing changing the name to GoDaddy Engineering.

feat(brand): update name to GoDaddy Engineering

---

_posts/2018-06-06-cicd-best-practices.md
_posts/2018-06-19-jenkins-build-monitoring-plugin.md
_posts/2019-06-18-react-native-community-contribution-datetimepicker-component.md

Moving forward, all links to other content needs to be relative links! In the future, when requests to godaddy.com/engineeing are proxied to the github.io, the user should stay on godaddy.com/engineeing when clicking links. This does not change any behavior on https://godaddy.github.io/.

Modified blog absolute links to be relative links

---

_includes/component/all-projects.html
featured-projects.html

Measuring this change:
We currently have a link to github.com/godaddy in the site footer, but I thought it was hard to find. I'll compare outgoing traffic to that url as well as outgoing traffic to github links on the featured projects page for the month before and after this change.

feat(projects): make it easier to navigate to all godaddy projects

---

_config.yml
_includes/block/head.html
_includes/component/author-panel.html
_includes/component/navigation.html
_includes/component/post-card.html
_includes/component/recent-posts.html
_layouts/post.html
_posts/2018-06-06-cicd-best-practices.md
_posts/2018-06-12-announcing-winston-3.md
_posts/2018-06-19-jenkins-build-monitoring-plugin.md
_posts/2018-07-10-react-native-wdio.md
_posts/2018-10-16-cypress-vs-selenium.md
_posts/2018-10-28-google-lighthouse-as-a-service-lighthouse4u.md
_posts/2019-02-26-software-vpn-channel.md
_posts/2019-04-09-announcing-exemplar.md
_posts/2019-04-16-kubernetes-external-secrets.md
_posts/2019-05-22-testing-react-native-using-ekke.md
_posts/2019-06-18-react-native-community-contribution-datetimepicker-component.md
_posts/2019-06-25-asherah-opensource-app-encryption-sdk.md

modified layouts and components to utilize Jekyll Liquid Filters as Well as prepending the site.baseurl to relative links in posts. This does not have any change to the site other than allowing us to make the switch to a new baseurl when the blog moves to /engineering.

Utilize Jekyll Liquid Filters and baseurl

---

404.md

I am 100% open to content changes, but this at least handles the error rather than showing the [currently generic github pages response](https://godaddy.github.io/seamlessly-connecting-domains-services-domain-connect-2-0/)

Handle 404 errors

---

_config.yml
_includes/block/head.html

The canonical link element is still pointing to the blogs old URL, and I believe this is the root cause of some issues with the content being shared on various social platforms.
This PR corrects that, and also corrects an issue with the OG image not including the base URL.
Showing a blog post still loading images correctly in local env:
Showing the canonical link reflecting the configuration file settings:

fix: canonical links still pointing to the the old blog URL

---

_posts/2019-05-22-testing-react-native-using-ekke.md

There was a persistent message coming up when running Jekyll locally:
```
Liquid Warning: Liquid syntax error (line 108): Expected end_of_string but found colon in "{{ backgroundColor: 'red', width: this.props.width, height: this.props.height }}" in engineering/_posts/2019-05-22-testing-react-native-using-ekke.md
```
In looking into this, I realized that part of the post is not even rendering properly! Here are before and after shots for reference:
Before:
After:

Fix a couple of rendering issues on the Ekke post

---

featured-projects.html

After talking this over with a few people and looking what it actually did (searches the 11 projects on the current page) we decided that this wasn't as useful as originally hoped, and could potentially give the impression that it was searching all of our projects. So this is being removed for now.

Remove the search bar for now; was proving more deceptive than useful

---

code-of-conduct.html

When the blog was first started, I recommended using the Django code of conduct, as it has done well for that community. Now as our open source work and presence has grown, we've shifted toward adopting the Contributor Covenant for our open source projects. This brings the blog into alignment with that adoption.

Swap to the Contributor Covenant to match our OSS projects

---

code-of-conduct.html
github-orgs.html
slack.html

Our current story for joining Slack has not been great. For example, in the [tartufo contributing doc](https://tartufo.readthedocs.io/en/stable/CONTRIBUTING.html), we point directly to the Slack server, but do not tell users how to get an invitation. In the [kubernetes-external-secrets README](https://github.com/godaddy/kubernetes-external-secrets#readme), we link to the invitation page, but not the Slack server itself. And every time somebody asks me how to get to our OSS Slack server, I have to go look up the invitation link. This one page should ease that whole story. Want to join us on Slack? Go look at this one page.
And here is what it looks like:
This is very heavily shamelessly based on http://dctech.chat/ 😄

Add a page about joining us on Slack
